name: Deploy subgraph

on:
  push:
    branches:
      - stable
      - sandbox
      - DD-2159-integrate-yearn-affiliate-token

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - name: Build and deploy Stable Mainnet
        if: github.ref == 'refs/heads/stable'
        uses: ./.github/actions/deploy-subgraph
        with:
          thegraph_access_token: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}
          type: stable-mainnet

      - name: Build and deploy Stable Rinkeby
        if: github.ref == 'refs/heads/stable'
        uses: ./.github/actions/deploy-subgraph
        with:
          thegraph_access_token: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}
          type: stable-rinkeby

      - name: Build and deploy Sandbox Mainnet
        if: github.ref == 'refs/heads/sandbox'
        uses: ./.github/actions/deploy-subgraph
        with:
          thegraph_access_token: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}
          type: sandbox-mainnet

      - name: Build and deploy Sandbox Rinkeby
        if: github.ref == 'refs/heads/sandbox'
        uses: ./.github/actions/deploy-subgraph
        with:
          thegraph_access_token: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}
          type: sandbox-rinkeby

      - name: Build and deploy Breaking Sandbox Mainnet
        if: github.ref == 'refs/heads/DD-2159-integrate-yearn-affiliate-token'
        uses: ./.github/actions/deploy-subgraph
        with:
          thegraph_access_token: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}
          type: breaking-sandbox-mainnet

      - name: Build and deploy Breaking Sandbox Rinkeby
        if: github.ref == 'refs/heads/DD-2159-integrate-yearn-affiliate-token'
        uses: ./.github/actions/deploy-subgraph
        with:
          thegraph_access_token: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}
          type: breaking-sandbox-rinkeby
